LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 100000
TimeToSleep: 0
client_id: 037deee7-83d1-467b-9cdb-802dc2bad263
client_key: jdrh8UepzYZ7UesMKzCNXfcXZ2Z6yJGt
client_secret: fhDmG4CJU7Wr27V3EesGh7v7Navq7kb97bctBN4ffCR8AgzdSsaUbdrd6CX3HSmF
portal_url: int.opsramp.net
AWS_TOKEN: rxcn3HgBTx2SAXXunMRSdJCzQY36Gbfq
AZURE_TOKEN: F3gX8wYpPGhCRpes3PvMNJxXd6dxTQb8
GCP_TOKEN: bxdhXCAFeHSd57dZaGsTDgk9hqwrnfg6
AWS_BUCKETNAME : logsvalidation-int
LOGS_GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAASkbKjyE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=x1rUpPmWjpbNRqzbWAr1oYc7dFJhpJ2p2Wa9nXDhJSM%3D
TRACES_GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAASkbKjyE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=x1rUpPmWjpbNRqzbWAr1oYc7dFJhpJ2p2Wa9nXDhJSM%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 
Portal_Name: INT
TracingService: PetClinicSampleApp
TracingOperation: /vets.html
ArchivalFileSize: 20M
