LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 100000
TimeToSleep: 0
client_id: 037deee7-83d1-467b-9cdb-802dc2bad263
client_key: jdrh8UepzYZ7UesMKzCNXfcXZ2Z6yJGt
client_secret: 8k2DTVKZJwsDqeMkKAXTSx48snEBGtPJQfqYVmgbxsA8A4QZAXhA6zmpPengEbT9
portal_url: int.opsramp.net
AWS_TOKEN: rxcn3HgBTx2SAXXunMRSdJCzQY36Gbfq
AZURE_TOKEN: F3gX8wYpPGhCRpes3PvMNJxXd6dxTQb8
GCP_TOKEN: bxdhXCAFeHSd57dZaGsTDgk9hqwrnfg6
AWS_BUCKETNAME: logsvalidation-int
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
Portal_Name: INT
ArchivalFileSize: 20M

