LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 100000
TimeToSleep: 0
client_id: 69086467-9c5c-484f-bfb1-0f08afd33cc5
client_key: pKt8fncMfuAunuEu8kUNxQvRshfYTSYU
client_secret: AQupEfvWsFuPjYxWnFYeJKzE2Eby2z6PV84tEaRj67SfYTpnANT7VFFZMkvMNN2p
portal_url: int.opsramp.net
AWS_TOKEN: 58sydcSN2U4fxZVZxaGWE24n5SnB6y6v
AZURE_TOKEN: GgWpktaQpYUK2bSypadmKq4XUhCS8EzS
GCP_TOKEN: UYSG2hJdt4S5uPdCyBGWDwRPHS2AAe4G
AWS_BUCKETNAME : logs-validation
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 
Portal_Name: INT

