LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 100000
TimeToSleep: 0
client_id: a73960de-84fc-471a-8183-c1e5c7ae5bcb
client_key: tSQ7USRYm3jVpj2dnk7rt4g5RGumCASP
client_secret: GBfKMNRNb3AVqjthxv9Pa8GD2tAsXjTYjTtURnwCbqrNEcQZtruYFbMGC7mZwKPc
portal_url: int.opsramp.net
AWS_TOKEN: R8vCm39UGgpeVyX2Wa4zewP5SxGYkxJQ
AZURE_TOKEN: JP9X4aS7RyMpCt6EcecyQwrU3W27FKYG
GCP_TOKEN: QDNz5Rn6JfgAtCsKgt3H7GkPsvHTmvFQ
AWS_BUCKETNAME : logs-validation
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 
Portal_Name: INT

