LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 100000
TimeToSleep: 0
client_id: 037deee7-83d1-467b-9cdb-802dc2bad263
client_key: 7TCWHgrmSgBJX6Amhk7TJMWAjhYBwEe7
client_secret: rePNNsK5Fhg89u7S7xQFtFv9ZpNcNmbEtwec4k6VbSw4Wsnut9P5rHKuDkKtMaEG
portal_url: int.opsramp.net
AWS_TOKEN: rxcn3HgBTx2SAXXunMRSdJCzQY36Gbfq
AZURE_TOKEN: F3gX8wYpPGhCRpes3PvMNJxXd6dxTQb8
GCP_TOKEN: bxdhXCAFeHSd57dZaGsTDgk9hqwrnfg6
AWS_BUCKETNAME : logs-validation
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 
Portal_Name: INT
