pipeline {
  agent any
  stages {
    stage('version') {
      steps {
        sh 'python3 --version'
      }
    }
    stage('ObservabilityAutomation') {
      steps {
        sh 'python3 LogsAutomation-INT/ObservabilityAutomation-INT/LogsAutomation/LogsValidation.py'
        sh 'python3 LogsAutomation-INT/ObservabilityAutomation-INT/LogsAutomation/TracingValidation.py'
      }
    }
  }
} 
